//! DTS-backed metadata lookup helpers.
//!
//! This module provides read-only access to the static metadata generated by
//! `build.rs` from a Merlin-compatible DeviceTree source.
//!
//! # Notes
//!
//! The generated tables may be empty when `MERLIN_DTS` is not set at build
//! time. In that case, every lookup simply returns `None`.

use crate::types::{DeviceType, UsbMaximumSpeed};

include!(concat!(env!("OUT_DIR"), "/dts_generated.rs"));

/// Returns the device metadata matching a Merlin device kind and DTS label.
///
/// The returned reference points to static metadata generated at build time
/// from the DTS backend.
///
/// Returns `None` when the label is unknown for the requested kind or when the
/// kind has no DTS-backed metadata (for example `DeviceType::Ext`).
///
/// # Example
///
/// ```no_run
/// use camelot_merlin::dts;
/// use camelot_merlin::types::DeviceType;
///
/// let label = 0x4000_3800;
/// let _devinfo = dts::lookup_devinfo(DeviceType::Usart, label);
/// ```
pub fn lookup_devinfo(kind: DeviceType, label: u32) -> Option<&'static crate::types::DevInfo> {
    match kind {
        DeviceType::I2c => I2C_DEVICES
            .iter()
            .find(|dev| dev.devinfo.id == label)
            .map(|dev| &dev.devinfo),
        DeviceType::Spi => SPI_DEVICES
            .iter()
            .find(|dev| dev.devinfo.id == label)
            .map(|dev| &dev.devinfo),
        DeviceType::Usart => USART_DEVICES
            .iter()
            .find(|dev| dev.devinfo.id == label)
            .map(|dev| &dev.devinfo),
        DeviceType::Can => CAN_DEVICES
            .iter()
            .find(|dev| dev.devinfo.id == label)
            .map(|dev| &dev.devinfo),
        DeviceType::Usb => USB_DEVICES
            .iter()
            .find(|dev| dev.devinfo.id == label)
            .map(|dev| &dev.devinfo),
        DeviceType::Ext => None,
    }
}

/// Returns the input bus clock frequency in MHz for a labeled bus-backed device.
///
/// Supported kinds are I2C, SPI, USART and CAN. USB and EXT return `None`.
///
/// # Example
///
/// ```no_run
/// use camelot_merlin::dts;
/// use camelot_merlin::types::DeviceType;
///
/// let label = 0x4000_5400;
/// let _clock_mhz = dts::bus_clock_mhz(DeviceType::Spi, label);
/// ```
pub fn bus_clock_mhz(kind: DeviceType, label: u32) -> Option<u32> {
    match kind {
        DeviceType::I2c => I2C_DEVICES
            .iter()
            .find(|dev| dev.devinfo.id == label)
            .map(|dev| dev.bus_input_clock_freq),
        DeviceType::Spi => SPI_DEVICES
            .iter()
            .find(|dev| dev.devinfo.id == label)
            .map(|dev| dev.bus_input_clock_freq),
        DeviceType::Usart => USART_DEVICES
            .iter()
            .find(|dev| dev.devinfo.id == label)
            .map(|dev| dev.bus_input_clock_freq),
        DeviceType::Can => CAN_DEVICES
            .iter()
            .find(|dev| dev.devinfo.id == label)
            .map(|dev| dev.bus_input_clock_freq),
        DeviceType::Usb | DeviceType::Ext => None,
    }
}

/// Returns the maximum USB speed declared for the given USB device label.
///
/// # Example
///
/// ```no_run
/// use camelot_merlin::dts;
///
/// let label = 0x5000_0000;
/// let _speed = dts::usb_maximum_speed(label);
/// ```
pub fn usb_maximum_speed(label: u32) -> Option<UsbMaximumSpeed> {
    USB_DEVICES
        .iter()
        .find(|dev| dev.devinfo.id == label)
        .map(|dev| UsbMaximumSpeed::from(dev.maximum_speed))
}

/// Returns I2C child device metadata associated with an I2C controller label.
///
/// The slice length is clamped to the generated child array capacity to remain
/// robust even if DTS metadata and compile-time limits diverge.
///
/// # Example
///
/// ```no_run
/// use camelot_merlin::dts;
///
/// let label = 0x4000_5400;
/// let _children = dts::i2c_child_devices(label);
/// ```
pub fn i2c_child_devices(label: u32) -> Option<&'static [crate::types::DevInfo]> {
    I2C_DEVICES
        .iter()
        .find(|dev| dev.devinfo.id == label)
        .map(|dev| {
            let count = usize::try_from(dev.num_child_devices)
                .ok()
                .unwrap_or(0)
                .min(dev.child_devinfo.len());
            &dev.child_devinfo[..count]
        })
}
